version: "3.9"

services:
  prasetv_app:
    build: .
    expose:
      - 3000
    volumes:
      - db-data:/data
    command: >
      sh -c "
        if [ ! -f /data/prasetv.db ]; then
          echo '[INIT] Creating DB from schema...';
          sqlite3 /data/prasetv.db < /app/db/schema.sql;
        fi &&
        /app/server
      "

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - prasetv_app

volumes:
  db-data:
