// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Bookmark struct {
	ID        string
	Title     string
	Url       string
	ParentID  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
